# You could change these directories as you see fit
base_dir: '/data/CARD_AUX/LRS_temp/NABEC_RNA'
ont_ubam: '/data/CARD_AUX/LRS_temp/NABEC_RNA/SNAKEMAKE_TEST/ONT_UBAM'
dorado_model: 'dna_r10.4.1_e8.2_400bps_sup@v5.0.0'
pychopper_dir: '/data/CARD_AUX/LRS_temp/NABEC_RNA/SNAKEMAKE_TEST/PYCHOPPER'
mapping_dir: '/data/CARD_AUX/LRS_temp/NABEC_RNA/SNAKEMAKE_TEST/MAPPED'
assembly_dir: '/data/CARD_AUX/LRS_temp/NABEC_RNA/SNAKEMAKE_TEST/ASSEMBLY/'
isoquant_dir: '/data/CARD_AUX/LRS_temp/NABEC_RNA/SNAKEMAKE_TEST/ASSEMBLY/ISOQUANT'
stringtie_dir: '/data/CARD_AUX/LRS_temp/NABEC_RNA/SNAKEMAKE_TEST/ASSEMBLY/STRINGTIE'
merge_dir: '/data/CARD_AUX/LRS_temp/NABEC_RNA/SNAKEMAKE_TEST/ASSEMBLY/MERGED'

#these directories should be kept unchanged
genome: '/data/CARDPB/resources/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa'
sirvome: '/data/CARDPB/data/LRS_RNA/projects/cedrics_nabec/REFERENCES/SIRV/SIRV_ERCC_longSIRV_multi-fasta_20210507.fasta'
human_genedb: '/data/CARDPB/resources/hg38/gencode.v43.annotation.gtf'
sirv_genedb: '/data/CARDPB/data/LRS_RNA/projects/cedrics_nabec/REFERENCES/SIRV/SIRV_ERCC_longSIRV_multi-fasta_20210507.corrected.gtf'
script_dir: 'scripts/'

# you could change the the source sample file but specify the path and name accordingly
sample_file: 'input_example.txt'